[package]
version = "0.1.0"
name = "frontend"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
description = "SVG - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon = { path = "../../../crates/zoon" }
strum = { version = "0.20.0", default-features = false, features = ["derive"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
