[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
# wai-bindgen-rust = { path = "../../../../../../wai/crates/rust-wasm", features = ["macros"], default-features = false }
wai-bindgen-rust = { version = "0.2.1", features = ["macros"], default-features = false }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
