[workspace]
members = [
    "crates/hsluv_macro",
    "crates/route_macro",
    "crates/static_ref_macro",
    "crates/hsluv",
    "crates/moon",
    "crates/moonlight",
    "crates/mzoon",
    "crates/zoon",
]
