[package]
name = "frontend"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
publish.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon.workspace = true
wgpu = { version = "24.0.1", features = ["wgsl"], default-features = false }
winit = "0.30.9"

[features]
# @TODO replace `webgl` with `webgpu` once all relevant browsers and WebViews support WebGPU 
# NOTE: Compressed Wasm module with`webgpu` has 125KB, with `webgl` 534KB, see
# https://github.com/gfx-rs/wgpu/issues/1464
default = ["webgl"]
webgl = ["wgpu/webgl"]
webgpu = ["wgpu/webgpu"]
