# ======= ======= ======= =======-
#             GENERAL
# ======= ======= ======= =======-
my_api = "example.com/api"
pi = 3.14
favorite_languages = ["Rust", "Magmide", ["Gleam"]]
is_pig_pink = true
birthday = 1993-07-21T04:32:15+02:00

# ======= ======= ======= =======-
#            POSTGRES
# ======= ======= ======= =======-

[postgres]
user = { name = "postgres", password = "postgres" }
host = "localhost"
name = "example_db"

# ======= ======= ======= =======-
#            FACEBOOK
# ======= ======= ======= =======-

[facebook] 
app_id = "2333222321131223"
app_secret = "212a2a2a2a1111aa212aa12112aaa121"
