[package]
name = "tauri_ipc"
version = "0.1.0"
description = "Tauri Web FS"
authors = ["Martin Kavík <martin@kavik.cz>"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.10", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta.13", features = ["macos-private-api", "linux-ipc-protocol"] }
# tauri-bindgen-host = { git = "https://github.com/tauri-apps/tauri-bindgen", rev = "5eabe7b96c7b77f37d82bd2fe519a9e3e1377c52" }
