port = 8080
# port = 8443
https = false
cache_busting = true
backend_log_level = "warn" # "error" / "warn" / "info" / "debug" / "trace"

[redirect]
port = 8081
enabled = false

[cors]
origins = ["*"]

[watch]
frontend = [
    "public",
    "frontend/Cargo.toml",
    "frontend/src",
    "frontend/js",
    "../../crates/zoon/Cargo.toml",
    "../../crates/zoon/src",
    "../../crates/static_ref_macro/Cargo.toml",
    "../../crates/static_ref_macro/src",
]
backend = [
    "backend/Cargo.toml",
    "backend/src",
    "../../crates/moon/Cargo.toml",
    "../../crates/moon/src",
]
