[package]
version = "0.1.0"
name = "frontend"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Martin Kavík <martin@kavik.cz>"]
description = "Benchmark - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
 # @TODO add "fmt" feature back in the future
zoon = { path = "../../../../crates/zoon", features = ["static_ref"], default-features = false }
rand = { version = "0.8.3", features = ["small_rng", "getrandom"], default-features = false }
getrandom = { version = "0.2", features = ["js"], default-features = false }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
