[package]
version = "0.1.0"
name = "shared"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Martin Kavík <martin@kavik.cz>"]
description = "Time Tracker - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2018"

[dependencies]
moonlight = { path = "../../../crates/moonlight" }

[features]
frontend = ["moonlight/frontend"]
backend = ["moonlight/backend"]
