[package]
version = "0.1.0"
name = "frontend"
repository = "https://github.com/MoonZoon/MoonZoon"
authors = ["Martin Kavík <martin@kavik.cz>"]
description = "TodoMVC - MoonZoon example"
categories = ["MoonZoon", "example"]
license = "MIT"
readme = "../README.md"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[dependencies]
zoon = { path = "../../../crates/zoon" }
strum = { version = "0.21.0",  features = ["derive"], default-features = false }
uuid = { version = "0.8.2", features = ["wasm-bindgen", "v4", "serde"], default-features = false }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
